### PR TITLE
Add 'who?' link to notifications

### PR DESCRIPTION
**Pull request by BytewaveMLP**
## Briefly describe the changes you've made

  - Adds a "who?" link to notifications, which selects the notification subject when the link is clicked (if it isn't a system notificaiton). Allows you to find people who have sent you friend requests and see their connected social sites if they aren't easily visible on your screen.

## Screenshots of your new feature (if applicable)

"who?" link in notification box

## Is this related to an existing issue?

N/A

### CODE REVIEW

**Comment by Stubenhocker1399** [comment]
Maybe consider making this a nicer button than a text link?

**Comment by BytewaveMLP** [comment]
I chose the link because I didn't want it to be too invasive or disruptive. It's more of a hint than an actual button, which should be reserved for the actual notification actions. 🤷‍♂

**Comment by BytewaveMLP** [comment]
Promoting it to a button required using an inline style declaration, unfortunately, but now it looks like this:



I'm not sure how I feel about that, but it looks okay?

**Comment by Stubenhocker1399** [comment]
That looks fine to me. Did you test it what happens when the requesting user disconnects?

**Comment by BytewaveMLP** [comment]
The selection is still allowed to occur, and just selects the user as if they were online. Not sure how this would behave if lots of players are joining and leaving, but it seems to behave normally.

Annoyingly, ponies currently out of the rendered area when they sent the request won't have their pony data loaded at all. In this instance, there's not really a good way to select them, as there's no `selectById` function or similar as far as I can tell. I can prevent the select button from doing anything int his instance, but there's not a good way to make it start working again if the pony walks back into frame. Ideally, you wouldn't be sending cross-map friend requests, but such could arise when sending friend requests to party members.

**Pull request merged**
